<a href="https://colab.research.google.com/github/HAN-GEONHUI/test/blob/t_academy_%EC%88%98%EC%97%85_pandas/02_pandas(240827).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#업그레이드-> 판다스

#판다스를 개발한 사람들은 "차원"을 중심으로 여러 자료형!
#1차원:1차원 벡터-->series type
#2차원:2차원 행렬--> DataFrame Type *** 자주 사용되는 것 (비정형 특징들을 뽑아서 투입해야 한다.)
#3차원:3차원 텐서--> pannedl type
#그 이상의 고차원은 안함!!
#그 이상의 고차원은 Tensor-->TF/Pytorch: DL쪽이 중심!

#+특징: 인덱스를 내가 원하는 대로 만들 수 있음!
#       원하는 정보로 내가 접근도 가능함!!
        ==> "인덱스"내가 만든 것도 있고,,
            "인덱스"가 태생적인 정수쪽 인덱스도 있다!
#pandas의 개발히스토리가 있다.--> 파이썬으로 금융데이터를 처리하고 싶어요!!
#언제,얼마,
#장이 안열리는 날도 있음...->날짜 중심의 데이터가 빵구
#2024-02-28
#2024-03-02
#.....
#? 그러면 2024-05-08의 데이터는 얼마?
list.index(값)-->list에서 위치 정보로 조회!
#->pandas단점도 있음: 시간,숫자,텍스트,,여러 자료형 다 처리해야 하므로 속도가 느림-> 적당한 사이즈의 데이터 헨들링에는 좋다
#but) 큰사이즈,실시간 대용량 대응을 못함-> sql,gpu,spark를 써야 함.(몇백gb는 요거 써야 함)


In [ ]:
#예) 삼성전자 주가 데이터를 처리 하고 싶다.
# 종가 1개만 생각하고 80000,79000,83000,82000...
#--> 1차원 가격들만 모아둘 수 있음!!(리스트,array etc)
# ==> 1차원 가격들만 모아둘 수 있음!!!( 리스트, array etc)

# 오늘 가격은 얼마? ==> -1
# 지난 주 화욜은 얼마? ??? 몇 번쨰인지 고민을 해야함
# ===> 주말,,,,중간 공휴일,,,,
# ===> 몇 번째 데이터로 접근하기에 상당히 불편하다!
# ===> 정수인덱스 말고,,
#      내가 원하는 인덱스로 종가 데이터를 접근할 경로를 만들자!
#      (날짜가 그 중에 하나 후보!!!)

In [ ]:
import numpy as np
import pandas as pd
# 생성1) 쌩 파이썬의 리스트
stock_price_list = [ 10000, 10300, 9900, 10500, 11000 ]
# 생성2) numpy --> array
stock_price_arr = np.array(stock_price_list)
# 생성3) pandas -->1차원-->Series 자료형을 생성:S대문자
stock_price_Series = pd.Series( stock_price_list )

In [ ]:
stock_price_list

[10000, 10300, 9900, 10500, 11000]

In [ ]:
stock_price_arr

array([10000, 10300,  9900, 10500, 11000])

In [ ]:
stock_price_Series

0    10000
1    10300
2     9900
3    10500
4    11000
dtype: int64

In [ ]:
# 1번 주식 가격에 대한 접근
print( stock_price_list[0])
print( stock_price_arr[0])
print( stock_price_Series[0])

10000
10000
10000


In [ ]:
# 1번 주식 가격에 대한 접근
print( stock_price_list[0:4])
print( stock_price_arr[0:4])
print( stock_price_Series[0:4])

[10000, 10300, 9900, 10500]
[10000 10300  9900 10500]
0    10000
1    10300
2     9900
3    10500
dtype: int64


In [ ]:
# 내가 보고자 하는 것들이, 랜점하게 0번째 주가/4번째 주가만,,
stock_price_list[ [0,4]] #--> 리스트는 오류가 남

TypeError: list indices must be integers or slices, not list

In [ ]:
stock_price_arr[ [0,4]] # array는 왠만한거는 전부 됨

array([10000, 11000])

In [ ]:
stock_price_Series[ [0,4]]

0    10000
4    11000
dtype: int64

In [ ]:
# ==> 특별하게 나만의 인덱스를 지정하지 않으면,,
#     그냥 값들만 모아둔 친구라서,,태생적인 정수인덱스 기반만 가능!
# +++ 내가 직접 인덱스를 만들자!
# **** pandas는 꼭!!!! 인덱스를 달고 다닌다 *********

In [ ]:
stock_price_Series_index = pd.Series(
    #정보:진짜 리얼한 데이터들
    #내가 원하는 값에 접근할 수 있는 인덱스
    data = [10000, 10300, 9900, 10500, 11000],
    index = ["2024-08-01","2024-08-02","2024-08-03",
             "2024-08-04", "2024-08-5"]
)
stock_price_Series_index

2024-08-01    10000
2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
2024-08-5     11000
dtype: int64

In [ ]:
stock_price_Series_index[0]

<ipython-input-18-582ae4b44d1a>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stock_price_Series_index[0]


10000

In [ ]:
stock_price_Series_index[0:4]

2024-08-01    10000
2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
dtype: int64

In [ ]:
stock_price_Series_index["2024-08-02"]

10300

In [ ]:
stock_price_Series_index["2024-08-02":"2024-08-04"]
# ==> 정수 인덱스로 슬라이싱 하면 : 끝 점이 빠짐...
#     내가 만든 인덱스로 슬라이싱 하면 : 끝 점이 포함...

2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
dtype: int64

In [ ]:
stock_price_Series_index[ [0,4]]

<ipython-input-22-868bbe721acb>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stock_price_Series_index[ [0,4]]


2024-08-01    10000
2024-08-05    11000
dtype: int64

In [ ]:
stock_price_Series_index[ ["2024-08-02","2024-08-04"]]

2024-08-02    10300
2024-08-04    10500
dtype: int64

In [ ]:
stock_price_Series_index["2024-08-05"]
# 참고) 쌩 파이썬의 Dict의 Key처럼 Exact MAtching을 기본으로 함!!
# ==> 공백, 대소문자, 오타 등에 유의해야 함!!!!!

KeyError: '2024-08-05'

In [ ]:
stock_price_Series_index["2024-08-5"]

11000

In [ ]:
#numpy에서 하는게 다 됨
#--> 불리언 인덱싱!!!--> 조건 필터링이 가능해서 중요함
#여기서도 불리언 인덱싱이 가능함
#ex)주식 가격이 10000원이 넘는 데이터만 추려서 봅시다.

In [ ]:
stock_price_Series_index[stock_price_Series_index>10000]

2024-08-02    10300
2024-08-04    10500
2024-08-5     11000
dtype: int64

In [ ]:
#참고)dict와 상당히 유사! 동작도 유사하다 key_value
#     pandas              index(정수,내가 만든거)+value


In [ ]:
stock_price_Series_index.index

Index(['2024-08-01', '2024-08-02', '2024-08-03', '2024-08-04', '2024-08-5'], dtype='object')

In [ ]:
stock_price_Series_index.values

array([10000, 10300,  9900, 10500, 11000])

In [ ]:
stock_price_Series_index +100

2024-08-01    10100
2024-08-02    10400
2024-08-03    10000
2024-08-04    10600
2024-08-5     11100
dtype: int64

In [ ]:
#참고)in: 자료형이 파이썬의 dict--> key 중심으로 체크!!
#                  파이썬의 lsit--> value 중심으로 체크!!
#                  pandas에서는?--> index 중심으로 체크
#                                    (값 중심 아님!)

In [ ]:
"2024-08-03" in stock_price_Series_index

True

In [ ]:
"2024-08-05" in stock_price_Series_index

False

In [ ]:
"2024-08-5" in stock_price_Series_index

True

In [ ]:
stock_price_Series_index

2024-08-01    10000
2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
2024-08-5     11000
dtype: int64

In [ ]:
# 알아둘 사항 : 쌩 파이썬의 dict <---> pandas 유사함!!!
# ==> 데이터 수집에서 서로 상호호환이 가능함!!!!
# (뒤에 데이터 수집할 때 예로 볼 예정!!!!)

In [ ]:
s_data = {"APPL":1000, "MS":2000, "TSLA": 1500}
s_data

{'APPL': 1000, 'MS': 2000, 'TSLA': 1500}

In [ ]:
s_data["APPL"]

1000

In [ ]:
s_data[0]

KeyError: 0

In [ ]:
s_data_Series = pd.Series( s_data)
s_data_Series

APPL    1000
MS      2000
TSLA    1500
dtype: int64

In [ ]:
s_data_Series["APPL"]

1000

In [ ]:
s_data_Series[0]

<ipython-input-42-5ed2c8b0f14b>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s_data_Series[0]


1000

In [ ]:
#
s_data = {"APPL":1000, "MS":2000, "TSLA": 1500}
ticker = ["GOOGLE", "APPL", "MS","META"]
s_2 = pd.Series(s_data, index = ticker )
s_2

GOOGLE       NaN
APPL      1000.0
MS        2000.0
META         NaN
dtype: float64

In [ ]:
#결측치에 대한 발생을 늘 염두에 두어야 한다.
#why? 결측치 생긴다고 경고나 에러가 없음
#pandas :NaN
#mysql:null-->isnull.is not null

In [ ]:
s_1 = pd.Series(s_data)
s_1

APPL    1000
MS      2000
TSLA    1500
dtype: int64

In [ ]:
s_2

GOOGLE       NaN
APPL      1000.0
MS        2000.0
META         NaN
dtype: float64

In [ ]:
s_1+s_2
#--> numpy의 기본적인 벡터연산의 특징!
#    단순 순서 중심의 벡터연산이 아니라 index 중심의 벡터 연산으로 동작을 함
#+++ pandas 에서는 index에 대해서 or처리 하는 경우 들이 있어 원하지 않는 row가 생성될 수 있음
#    꼭 데이터 수를 체크하기

APPL      2000.0
GOOGLE       NaN
META         NaN
MS        4000.0
TSLA         NaN
dtype: float64

In [ ]:
# 참고) 결측치 데이터에 대한 처리!!!
# --> 자주 사용되는 메서드
#     .isnull() : 너 값이 결측값이냐? --> T/F
#     .notnull() :너 값이 정상값이냐? --> T/F

In [ ]:
temp = s_1+s_2
temp

APPL      2000.0
GOOGLE       NaN
META         NaN
MS        4000.0
TSLA         NaN
dtype: float64

In [ ]:
temp.isnull()

APPL      False
GOOGLE     True
META       True
MS        False
TSLA       True
dtype: bool

In [ ]:
temp(temp.isnull())

TypeError: 'Series' object is not callable

In [ ]:
temp[temp.isnull()]

GOOGLE   NaN
META     NaN
TSLA     NaN
dtype: float64

In [ ]:
temp[temp.notnull()]

APPL    2000.0
MS      4000.0
dtype: float64

In [ ]:
#주의
#위의 isnull(),notnull() 메서드들이 FM적으로 맞는 말이고 맞는 기능
#실제 데이터를 처리하다 보면 이런 단순 기능으로 빠지는 얘들이 있음
#NaN이 아니라 다른 문자로 찍혀서 들어옴 그리고 None으로 들어오면 못 찾음

#실제 코드적인 부분만이 아니라 실제 데이터를 보면서 작업을 해야 한다.
#-> 결측 데이터에 있어서 빈문자열,None,NaN을 구분하면서 꼭 하기
#DB는 NaN 아니면 다 튕겨내서 걱정없지만 파이썬은 다 받아줘서 문제임 ㅎㅎ

In [ ]:
#기타
temp.ndim

1

In [ ]:
temp.shape

(5,)

In [ ]:
len(temp)

5

In [ ]:
temp.dtype

dtype('float64')

In [ ]:
## pandas 값에 대한 접근 방식:FM적인 방법

In [ ]:
# 기존의 방식 : 인덱스 자리에 내가 원하는 것을 요청하자!
#               -> 정수, 슬라이싱, 리스트etc
#               + 내가 만든거, 내가 만든거로 슬라이싱, 내가 만든걸로 리스트,,
#               + 조건식 기반의 불리언 인덱싱(필터링)
# ==> 앞의 결론 : pandas[ 대충 던지면 된다!! ]
# 값들이 많은 경우에 있어서는 속도차이가 상당히 나요!
# ==> FM적인 방법을 사용해야 속도를 보장받을 수 있음!
#     상당히 차이 남!!!

In [ ]:
# pandas는 FM적으로 명시적으로 접근하는 방법을 만들어 둠!!!
# 값에 대한 접근을 바라보는 관점 : 1개 값 접근 vs 여러개 값
#   1개 값에 접근  1) at  : 내가 만든 인덱스로 1개 값 접근!!!
#                  2) iat : 태생적인 정수인덱스1개 값 접근!!!!
#   여러개 값에 접근 1) loc : 내가 만든 인덱스로 여러개 값 접근!!
#                    2) iloc :태생적인 정수인덱스로 여러개 값 접근!!

# 참고) 이 부분들은 계속 버전에 따라서 변경되고 있음!!!!
#      ==> 단순 구글링을 하면,,오래전 자료가 나와서 안 맞을 수 있음.!!
#      ==> 최근 문서 기준으로..

# 결론!!!) 내가 만든 인덱스로 접근 vs 태생적인 정수값을 접근!!!
#        + 1개 값을 접근을 할 것인가 vs 여러개 값을 요청할 것인가!!!

# 참고) 1개 값을 iloc , loc 로도 가능은 함!!!
#       데이터가 많으면 속도가 차이가 남!!!!!

In [ ]:
stock_price_Series_index = pd.Series(
    #정보:진짜 리얼한 데이터들
    #내가 원하는 값에 접근할 수 있는 인덱스
    data = [10000, 10300, 9900, 10500, 11000],
    index = ["2024-08-01","2024-08-02","2024-08-03",
             "2024-08-04", "2024-08-5"]
)
stock_price_Series_index

2024-08-01    10000
2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
2024-08-5     11000
dtype: int64

In [ ]:
stock_price_Series_index[0]
# ==> 비공식적인 방법 : 간단히 처리하다 확인용으로 탐색으로는 괜찮음!!
# ==> 100만 데이터 처리에서는 노답!(속도가 많이 차이남)

In [ ]:
#ex)정수 인덱스로 접근&0번째 1개 값 접근 FM
stock_price_Series_index.iat[0]

10000

In [ ]:
stock_price_Series_index.iloc[0]
#일반적으로 속도:[0]>>iloc[0]>>iat[0]
#명확히 1개 값을 접근한다면 at/iat로 사용하세요


10000

In [ ]:
#예) 2024년 8월 4일 주식 가격은 얼마에요?
#--> 내가 만든 인덱스 &1개 요청 :at
stock_price_Series_index.at["2024-08-04"]

10500

In [ ]:
stock_price_Series_index.iat["2024-08-04"]

ValueError: iAt based indexing can only have integer indexers

In [ ]:
# 예) 0번쨰 부터 4번째 날의 주식 데이터를 보여주세요!!!
stock_price_Series_index[:4]

2024-08-01    10000
2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
dtype: int64

In [ ]:
stock_price_Series_index.iloc[:4]

2024-08-01    10000
2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
dtype: int64

In [ ]:
stock_price_Series_index["2024-08-02":"2024-08-04"]

2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
dtype: int64

In [ ]:
stock_price_Series_index.loc["2024-08-02":"2024-08-04"]

2024-08-02    10300
2024-08-03     9900
2024-08-04    10500
dtype: int64

In [ ]:
#참고) 수치연산을 하는 numpy를 포함 --> 간단한 연산을 내포

In [ ]:
stock_price_Series_index.sum()

51700

In [ ]:
stock_price_Series_index.count()

5

In [ ]:
stock_price_Series_index.max()

11000

In [ ]:
# 참고) pandas 자체 메서드 이외에 파이썬 함수, 외부 함수...
sum(stock_price_Series_index)

51700

In [ ]:
max(stock_price_Series_index)

11000

In [ ]:
# 정리
# 쌩 파이썬의 리스트 --> numpy array ---> pandas Series
#                                             1D
#                                      index(정수,내가 만든거)
#                                           at/iat/loc/iloc
#                                        벡터연산기본!!(index중심)